# Wrap all comments and lines to 80 characters
chain_width                   = 100
comment_width                 = 95
edition                       = "2021"
fn_single_line                = true
max_width                     = 95
single_line_if_else_max_width = 100
unstable_features             = true
use_small_heuristics          = "Max"
wrap_comments                 = true
